### PR TITLE
Edit team branch

### PR DESCRIPTION
**Pull request by CS673S17-Team-3**
Added creator class to Room model

### CODE REVIEW

**Comment by CS673S17-Team-3** [comment]
I think everyone will have to rerun `python manage.py makemigrations` after integrating this branch because the database will have to change. The creator will probably need a default value

**Comment by oliver-nowak** [comment]
@CS673S17-Team-3 lgtm

**Comment by oliver-nowak** [comment]
@CS673S17-Team-3 i fixed a merge conflict in your test file.

**Comment by ashsingh21** [comment]
LGTM

**Pull request merged**
