### PR TITLE
RestAPI

### PR DESCRIPTION
**Pull request by sonmn**
Refractor the RestAPI so that we can query on user and room independently.

### CODE REVIEW

**Comment by oliver-nowak** [comment]
@sonmn why are there 2 jar files included in this PR ? what is their purpose ?

**Review by oliver-nowak — CHANGES_REQUESTED** [review]
@sonmn it looks like you inadventantly added 2 jar files. let's remove those, and then we can merge this in. looks good otherwise! :)

**Comment by sonmn** [comment]
Thanks I will remove those files right away.

**Comment by CS673S17-Team-3** [comment]
LGTM

**Pull request closed without merging**
